### ISSUE TITLE
Adds a space after successful completion of directory names, instead of a slash

### ISSUE THREAD

**Issue by pdg137** [szermatt/emacs-bash-completion#11]
If you type a directory followed by tab, for example "/etc TAB", this package will add a space instead of a slash, which makes it hard to tab-complete paths with multiple components.  (Observed with Emacs 24.5.1 / Ubuntu 16.04).

**Comment by tddsg** [comment]
I encountered the same issue of adding an extra space, but with the first word of the command. 
I posted a question describe this issue in Emacs StackExchange (before I discovered this issue in GitHub)
https://emacs.stackexchange.com/questions/35115/how-to-prevent-the-completion-feature-of-emacs-shell-from-adding-an-extra-space
