### ISSUE TITLE
Extend to work in sh-mode

### ISSUE THREAD

**Issue by nverno** [szermatt/emacs-bash-completion#13]
I love this package!  It seems fairly easy to extend it to work in `sh-mode` with the following
redefinition of `comint-line-beginning-position`

```
(defun bash-completion-sh-complete ()
  (cl-letf (((symbol-function 'comint-line-beginning-position)
             #'(lambda ()
                 (save-excursion
                   (sh-beginning-of-command)
                   (point)))))
    (bash-completion-dynamic-complete)))

(add-hook 'completion-at-point-functions
          'bash-completion-sh-complete nil 'local)

```

This works well for me so far, but haven't tested it thoroughly.  Is this necessary, or am
I doing something unneeded with this?

**Comment by Ambrevar** [comment]
Same thing for eshell, with `(save-excursion (eshell-bol) (point))` instead of `comint-line-beginning-position`.

Would it be possible to refactor the function parameters so that it takes either a string or 2 positions?

**Comment by szermatt** [comment]
f63915492574c6da806010c1fb7d203563c47d96 introduces
  bash-completion-dynamic-complete-nocomint (start pos)

**Comment by Ambrevar** [comment]
Thanks for this addition.

I've just tested it and I don't seem to be able to complete anything but files.
`ls --<TAB>` completes into
```
--foo
--bar
```
assuming `foo` and `bar` are in the current directory.

**Comment by szermatt** [comment]
Where did you set the start point you passed to the function? It must be set at the beginning of the command (on the "l" of "ls) From your description, it sounds like you set start and end at (point).

**Comment by Ambrevar** [comment]
Forgot to mention the call:
```
(defun eshell-bash-completion ()
  (while (pcomplete-here
          (nth 2 (bash-completion-dynamic-complete-nocomint (save-excursion (eshell-bol) (point)) (point))))))
```
The former code was
```
(defun eshell-bash-completion ()
  (while (pcomplete-here
          (cl-letf (((symbol-function 'comint-line-beginning-position)
                     #'(lambda () (save-excursion (eshell-bol) (point)))))
            (nth 2 (bash-completion-dynamic-complete))))))
```
used to work when I first posted on this issue, it does not anymore.  Something got wrong somewhere else.  Could be on my end too.

**Comment by szermatt** [comment]
I can reproduce this behavior if there is no programmable completion registered for "ls", even when using bash-completion-dynamic-complete, then what follows -- gets expanded as file completion. Something's not right. I'll have a look. 

However, when there is programmable completion registered for "ls", I get the expected argument completion when I use your code (I didn't use complete, just printed out the result)
Something's wrong with the latest version, but it doesn't look like it's specific to the -nocomint function.

**Comment by Ambrevar** [comment]
Indeed, as you can see from my last code snippet, `bash-completion-dynamic-complete` is also affected.

**Comment by szermatt** [comment]
It should work now. Thank you for the report! It was a silly old bug that must have caused quite some confusion. 

Any luck getting full completion to work in eshell?

**Comment by Ambrevar** [comment]
Thank you, all good now.

Completion is a wonder in Eshell thanks to those simple lines:
```
(when (require 'bash-completion nil t)
  (setq eshell-default-completion-function 'eshell-bash-completion))

(defun eshell-bash-completion ()
  (while (pcomplete-here
          (nth 2 (bash-completion-dynamic-complete-nocomint (save-excursion (eshell-bol) (point)) (point))))))
```

I recommend using Helm as a selection menu.  (Don't know if it works with Ivy.)

Bash completion is sometimes lacking.  The [fish shell](http://fishshell.com/) arguably provides better completion.
I hook it into Eshell with the a similar function.  See my [dotfiles](https://github.com/Ambrevar/dotfiles/blob/master/.emacs.d/lisp/init-evil-eshell.el).
