### ISSUE TITLE
Completion quotes = as \=

### ISSUE THREAD

**Issue by svend** [szermatt/emacs-bash-completion#18]
When I complete a flag that uses `=`, it gets completed as `\=`. This is a minor cosmetic issue, since the quoted version works fine. When I use bash-completion outside Emacs, this does not occur.

To reproduce:

```
$ emacs -Q
```

Evaluate the following:

```
(package-initialize)
(setq bash-completion-args '("--noediting" "--login"))
(setq bash-completion-prog "bash")
(require 'bash-completion)
(bash-completion-setup)
```

```
M-x shell
$ kubectl --context<tab>
$ kubectl --context\=
```

I notice the completion string in the `bash-completion` buffer does not include the backslash.

I'm using the latest version of bash-completion from Melpa.

**Comment by szermatt** [comment]
Yes, quoting = was a bit annoying and unnecessary. It should be gone, now with fix 8ca917f
