### ISSUE TITLE
Recent changes to introduce variable bash-completion-start-files breaks completion

### ISSUE THREAD

**Issue by CarlsonP4** [szermatt/emacs-bash-completion#21]
bash-completion-comm: Symbol’s value as variable is void: startfile1

**Comment by kfogel** [comment]
I think there are actually two problems, both introduced to the function `bash-completion-require-process` in commit 21149fdc.

One problem is that the name of the `dolist` loop variable is `start-file`, but is called `startfile1` in the body of the `dolist`.  The second problem is that there is a missing conditional (either `if` or `when`) at the start of the body.

I have a PR to fix both, which I'll submit in a moment.

**Comment by kfogel** [comment]
Okay, PR #22 ready.

**Comment by CarlsonP4** [comment]
Wow! That was remarkable quick. Thanks!

**Comment by kfogel** [comment]
You're very welcome; I hope @szermatt gets a chance to merge it soon.

**Comment by szermatt** [comment]
I merged it last week and it looks fine. Thank you for the fix! Sorry for breaking completion. I'm currently trying to set things up to avoid such issues.

**Comment by CarlsonP4** [comment]
Thank you. No problem about the "breaking". These things happen, and I think your work to avoid such things in the future is awesome. I saw from the commit history that most of the recent work was to improve the test infrastructure. I really appreciate the emacs module and all your hard work!
