### ISSUE TITLE
Further customization of bash-completion-nospace

### ISSUE THREAD

**Issue by nverno** [szermatt/emacs-bash-completion#36]
Hi,
How would you feel about `bash-completion-nospace` have an additional
option to allow for only adding a space when not completing in strings?

For example, a common case arises when entering a quoted path with
environment variables, eg. `"$HOM"`, and bash wants to add a space here
which I think in most cases is unwanted.

I was thinking about adding a presumably minor modification to allow for an 
additional level of customization to disable the trailing space only in quoted 
(double/single) strings.  Any interest?

**Comment by szermatt** [comment]
Hi! 

I would like the behavior to be fully consistent with bash and keep the number of elisp-level customizations to a minimum. The completion itself is already highly configurable, through bash completion. 

What is bash behavior in that case? Is it consistent with emacs-bash-completion's? Is it possible to configure bash to behave the way you want, but not emacs-bash-completion?
