### ISSUE TITLE
directories not handled properly on "old bash"

### ISSUE THREAD

**Issue by ctanis** [szermatt/emacs-bash-completion#66]
With bash 4.2 and emacs 28.2 tab-completing a directory name expands the term as if it were a leaf in the filesystem, leaving a space after it and not allowing for deeper completion into the directory tree (rather than finishing it with a "/").  

```
commandline: <<EOF
if type __ebcpre &>/dev/null; then   __ebcpre; complete -p ls 2>/dev/null || compl$
EOF

status: 1
process: #<process shell>
output-buffer: <<EOF
EOF

emacs-version: "28.2"
bash-version: "4.2.46(2)-release"
bash-version: "4.2.46(2)-release"
completion-ignore-case: t
```

**Comment by szermatt** [comment]
Yes 😒  Appending / to directories properly requires Bash 4.4, as documented on the README.
