### ISSUE TITLE
Case-insensitive completion does not work

### ISSUE THREAD

**Issue by halloleo** [szermatt/emacs-bash-completion#7]
On OSX (Emacs 24.4, OSX 10.9) I cannot get **case-insensitive** completion to work. Outside emacs I managed this by putting the line

```
set completion-ignore-case On
```

in my ~/.inputrc file. In Emacs this file doesn't seem to be obeyed, despite the fact that emacs-bash-completion does use a real shell behind the scene to do the completions.

The Emacs-internal variables for case-insensitivity do not make any difference either.

**Comment by halloleo** [comment]
I played a bit with `completion-ignore-case` (inspired by an [answer to my stackoverflow question](http://stackoverflow.com/a/29162879)): Even when I use bind *in the part of `.bashrc` which is used for the completion shell* (see below) I do not get it to work.

```
if [[ ( -z "$INSIDE_EMACS" || "$EMACS_BASH_COMPLETE" = "t" ) ]]; then
   bind 'set completion-ignore-case on'
   [ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion
fi
```

You say readline isn't used in that shell. So in `bash-completion.el` I switched on readline for the shell completion process:

```
	    (setq process
		  (start-process
		   "*bash-completion*"
		   (generate-new-buffer-name " bash-completion")
		   bash-completion-prog))
		   ;;"--noediting"))
            ...
```
but it does not make any difference. Any idea why not?

**Comment by szermatt** [comment]
The case-insensitive setting set in .inputrc should now be respected with the latest version when using bash 4.
