### ISSUE TITLE
Completion with alias doesn't work

### ISSUE THREAD

**Issue by johngavingraham** [szermatt/emacs-bash-completion#75]
Regular completion works, e.g. at a shell with `ls d` + TAB:

```
commandline: <<EOF
if type __ebcpre &>/dev/null; then   __ebcpre; __EBCWRAPPER='COMP_LINE='\''ls d'\''; COMP_POINT=$(( 1 + ${#COMP_LINE} )); COMP_CWORD=1; COMP_WORDS=( ls d ); _comp_complete_longopt ls d ls' __ebcompgen -F __ebcwrapper -- d; else   echo ==emacs==nopre=${BASH_VERSION}==.;   __ebcp=("$PS1" "$PROMPT_COMMAND");  unset PS1 PROMPT_COMMAND;fi;
EOF

status: 0
process: #<process shell>
output-buffer: <<EOF
dockerfile/
docs/
driveorin-manager.env
driveorin-manager
driveorin-test-manager.env
driveorin-test-manager
EOF

emacs-version: "29.4"
bash-version: "5.2.32(1)-release"
bash-version: "5.2.32(1)-release"
context: #s(completion "ls d"
              ("ls" "d")
              1 "d" 25019 "d" nil
              ("-F" "_comp_complete_longopt")
              "\"'><=;|&(:" nil)
```

But I have the following alias set up:

```
$ alias ll
alias ll='ls -lFh --color=auto'
```

And at the same location, completing `ll d` doesn't work:

```
commandline: <<EOF
if type __ebcpre &>/dev/null; then   __ebcpre; __EBCWRAPPER='COMP_LINE='\''ll d'\''; COMP_POINT=$(( 1 + ${#COMP_LINE} )); COMP_CWORD=1; COMP_WORDS=( ll d ); _comp_complete_minimal ll d ll' __ebcompgen -F __ebcwrapper -- d; else   echo ==emacs==nopre=${BASH_VERSION}==.;   __ebcp=("$PS1" "$PROMPT_COMMAND");  unset PS1 PROMPT_COMMAND;fi;
EOF

status: 0
process: #<process shell>
output-buffer: <<EOF
EOF

emacs-version: "29.4"
bash-version: "5.2.32(1)-release"
bash-version: "5.2.32(1)-release"
context: #s(completion "ll d"
              ("ll" "d")
              1 "d" 25228 "d" nil
              ("-F" "_comp_complete_minimal")
              "\"'><=;|&(:" nil)
```

I've checked in a regular terminal (Gnome Shell) at the same location and both `ls d` and `ll d` work as expected.

**Comment by szermatt** [comment]
Thank you for the bug report! It looks like the execution of _comp_complete_minimal isn't happening as it should.

I haven't been able to reproduce it yet. 

Could you give me the version of the bash-completion package you're using ? The version I'm using calls this function _minimal, so clearly there's a difference. How to get that version depends on your distribution and how you installed bash-completion. Under Debian, for example, it's displayed by` dpkg -l '*bash-completion*'`

Could you also double-check that you're using the latest version of bash-completion.el ? A bug was fixed a few weeks ago that could very well manifest in such a way.

**Comment by johngavingraham** [comment]
I use `use-package` and `auto-package-update` from http://melpa.org/packages/, my version (just done an update) is:

`bash-completion                20241118.1847  installed             Bash completion for the shell buffer.`

So it looks like maybe a fix just might not have have made it through to melpa quite yet?

**Comment by szermatt** [comment]
>So it looks like maybe a fix just might not have have made it through to melpa quite yet?

No, that version contains the fix, so it's another issue.

Could you also send me the version of the bash-completion package? I don't mean the version Emacs bash-completion.el, but rather the package that provides the bash completion scripts on your system. It usually comes with your Linux distribution.

To get that, just do:
`echo ${BASH_COMPLETION_VERSINFO[*]}`

and send me the output. (I proposed looking at the packages installed with your distribution, in a previous message, but this way is simpler.)

**Comment by johngavingraham** [comment]
Ah, I misunderstood.

```
$ echo ${BASH_COMPLETION_VERSINFO[*]}
2 13 0
```

For the record, in case it makes a difference I'm on Fedora 41:

```
$ dpkg -l '*bash-completion*'
dpkg-query: no packages found matching *bash-completion*
```

**Comment by szermatt** [comment]
Completion of aliases should work now even with version 2.13 of the bash-completion scripts, with the fix above. A new version with the fix will be available in melpa in a few hours. 

Please have a look let me know if that doesn't work for you.

**Comment by johngavingraham** [comment]
Works for me now - thanks very much @szermatt !
