### ISSUE TITLE
remote shell

### ISSUE THREAD

**Issue by rfru** [szermatt/emacs-bash-completion#8]
Is there a way to get this to work on remote shells?

**Comment by ryantm** [comment]
This totally seems worth doing! Any hints for how get started on implementing it?

**Comment by szermatt** [comment]
Most of the work should be in bash-completion-require-process. This is the function that returns the bash process to talk to. To support remote hosts, bash-completion-require-process would need to make sure that it starts bash on the right host and returns the appropriate process. 

1.  extend bash-completion-require-process to teach it about the "current host". This is the first difficulty. 

2. once you know what the current host it, you can start bash on the right host. In theory, it's just a matter of prepending 'ssh user@host ' to bash-completion-prog, but what if it asks for passwords? 

3. transform bash-completion-process into a map from user@host to process, to keep one process per host. You might want to get rid of processes unused after a long time. 

For 1 and 2, I expect that TRAMP provides everything that's needed, but it'll require digging into the .el files to understand what is available. The TRAMP documentation mentions that integration is possible, but doesn't explain how it would be done. See, for example https://www.gnu.org/software/tramp/#Remote-processes

**Comment by Alexander-Shukaev** [comment]
Looking forward to this one!

**Comment by montag451** [comment]
I've started to work on remote shell support and I have a working implementation that you can find [here](https://github.com/montag451/emacs-bash-completion/tree/remote-shell-support-rebase). It's still a "work in progress" but it is usable. I will make a pull request as soon as it is ready. Feel free to try it, any suggestions or comments are welcome!

**Comment by szermatt** [comment]
Support for tramp is available at HEAD, thanks to montag451 ! 

Caching of completion results is strongly recommended when using tramp. See the new customisation variable bash-completion-enable-caching. It's not enabled by default yet, because wordbreak completion don't work when caching is enabled. 

It requires Emacs 24.1 - but preferably later; I didn't try keep backward-compatibility for that new feature.
