### ISSUE TITLE
history is cluttered by commands called in elisp

### ISSUE THREAD

**Issue by JalapenoGremlin** [szermatt/emacs-bash-completion#9]
Is there a way to not have the commands called by bash-completion.el to not polute the bash history?

> [user@host ~]$ history
> 11830  ls -1 /boot/abi*
> 11831  PROMPT_COMMAND='';PS1='	$?'
> 11832  function __bash_complete_wrapper { eval $__BASH_COMPLETE_WRAPPER; n=$?; if [[ $n = 124 ]]; then  echo -n "bash-completion-wrapped-status=124"; return 1;  fi; }
> 11833  shopt -u checkjobs
> 11834  shopt -u mailwarn
> 11835  export MAILCHECK=-1
> 11836  export -n MAIL
> 11837  export -n MAILPATH
> 11838  function quote_readline { echo "$1"; }
> 11839  complete -p

bash-completion.el
```
	    (bash-completion-send "shopt -u checkjobs" process)
	    (bash-completion-send "shopt -u mailwarn" process)
	    (bash-completion-send "export MAILCHECK=-1" process)
	    (bash-completion-send "export -n MAIL" process)
	    (bash-completion-send "export -n MAILPATH" process)
	    ;; some bash completion functions use quote_readline to double-quote
	    ;; strings - which compgen understands but only in some environment.
	    ;; disable this dreadful business to get a saner way of handling
	    ;; spaces. Noticed in bash_completion v1.872.
	    (bash-completion-send "function quote_readline { echo \"$1\"; }" process)
	    (bash-completion-send "complete -p" process)

```

**Comment by szermatt** [comment]
Adding

        (bash-completion-send "unset HISTFILE" process)

to the list of elisp commands you listed above would do the trick. It's something that bash-completion.el should have by default; I'll send out a fix. 

If you want to avoid changing your .el file until this is fixed in bash-completion.el or the package you're using, you can also add the following to your .bashrc:

      if [[ "$EMACS_BASH_COMPLETE" = "t" ]]; then
        unset HISTFILE
      fi

**Comment by szermatt** [comment]
The fix that uses bash-completion-send is now on the github head (commit 7f4bcd03a8066a9758edd55b08a4094ccb3c2548)

**Comment by JalapenoGremlin** [comment]
Awesome. Thanks
